WIP

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -56,20 +56,20 @@ jobs:
          docker-compose -f $compose_location -p key-vault-pipe-test --ansi never up -d --remove-orphans
          #echo "Waiting for containers to be up..."
          #sleep 20
-         set -e
-         max_retries=6
-         retries=0
-         while [ $retries -lt $max_retries ]; do
-          docker-compose -f $compose_location ps -q
-          if docker-compose -f $compose_location ps -q | xargs -I {} docker inspect -f '{{ .State.Health.Status }}' {} | grep -q healthy; then
-            echo "Containers are healthy!"
-            exit 0
-          else
-            echo "Waiting for containers to be up and healthy..."
-            sleep 5
-            retries=$((retries+1))
-          fi
-         done
+         #set -e
+         #max_retries=6
+         #retries=0
+         #while [ $retries -lt $max_retries ]; do
+         # docker-compose -f $compose_location ps -q
+         # if docker-compose -f $compose_location ps -q | xargs -I {} docker inspect -f '{{ .State.Health.Status }}' {} | grep -q healthy; then
+         #   echo "Containers are healthy!"
+         #   exit 0
+         # else
+         #   echo "Waiting for containers to be up and healthy..."
+         #   sleep 5
+         #   retries=$((retries+1))
+         # fi
+         #done
          docker exec key-vault-pipe-test.key-vault dotnet test
          #while ! docker-compose ps --quiet; do
          #   echo "Waiting docker build and tests to be done..."
